BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE P08_Inventaire';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE P08_FigurineCaracteristique';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE P08_Collection';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE P08_seq_collection';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE P08_seq_inventaire';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW P08_InventairePossedeDetaille';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW P08_ListeDeSouhaits';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW P08_CompletionCollection';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;



BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE P08_update_prix';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION P08_nom_figurire';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION P08_figurine_dans_collection';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION P08_get_figurines_by_collection';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE P08_tab_fig';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE P08_fig';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE P08_tab_fig_cursor';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE P08_fig_cursor';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE P08_seq_log';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE P08_inventaire_log';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER P08_trigger_log';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE P08_seq_stat';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE P08_inventaire_stats';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER P08_trigger_stats';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;

COMMIT;
